#!/bin/bash
source $OPENSHIFT_HOMEDIR/python-2.6/virtenv/bin/activate
cd ${OPENSHIFT_REPO_DIR}/wsgi/projectname
NOW=$(date +"%F")
python manage.py dumpdata | /bin/gzip -v > ${OPENSHIFT_DATA_DIR}/mysql_dump_snapshot-$NOW.gz
python emailcron_helper.py
