#!/bin/bash
asd=`date +%M`
if [ ${asd:1} == "5" ] || [ ${asd:1} == "0" ]
then
    cd ${OPENSHIFT_DATA_DIR}
    rm -rf *
    source $OPENSHIFT_HOMEDIR/python-2.6/virtenv/bin/activate
    cd ${OPENSHIFT_REPO_DIR}/wsgi/projectname
    NOW=$(date +"%F")
    python manage.py dumpdata | /bin/gzip -v > ${OPENSHIFT_DATA_DIR}/mysql_dump_snapshot_$NOW.gz
    python emailcron_helper.py
fi
